server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location = /sw.js {
        add_header Cache-Control "no-cache, no-store, must-revalidate" always;
    }

    location = /app.html {
        add_header Cache-Control "no-cache, must-revalidate" always;
    }

    location = /calculateur.html {
        add_header Cache-Control "no-cache, must-revalidate" always;
    }
}
